workflows:
  main:
    name: Main Workflow
    scripts:
      - name: Install Node.js
        script: nvm install
      - name: Use Node.js
        script: nvm use
      - name: Install Dependencies
        script: npm ci
      - name: Build Android APK
        script: |
          npx react-native run-android --variant=release
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
