workflows:
  main:
    name: Main Workflow
    environment:
      node: latest
    scripts:
      - name: Install Dependencies
        script: npm install
      - name: Build Android APK
        script: |
          npx react-native run-android --variant=release
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
